version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    rebase-strategy: auto
    auto-merge: false
    commit-message:
      prefix: "chore"
